#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Image-Thumbnail
version:      0.01
version_from: Thumbnail.pm
installdirs:  site
requires:
    GD:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
